### ISSUE TITLE
<Directory ... > Allow from IP ignored

### ISSUE THREAD

**Issue by legecha** [vgno/mod_vgremoteip#1]
Presuming this is a feature of this module (I presume so because of the "The solution should work with deny/allow, mod_rewrite, etc." requirement on the blog post at http://tech.vg.no/2013/08/13/logging-the-correct-ip-address-using-apache-2-2-x/), when I put the following in a vhost config:

```
<Directory /path/to/folder/>
  AllowOverride All
  Order Deny,Allow
  Deny from All
  Allow from 123.45.67.89
</Directory>
```

it will not work and log `client denied by server configuration`.

**Comment by olesku** [comment]
Hello,

This should work, I just did a test and verified that it's working with the
exact same deny/allow configuration that you pasted.

Would appreciate if you could check a couple of things and get back to me.
- Check that the IP/subnet of the client that sets the forwarded-for header
  is listed in the VGTrustedProxy config parameter.
- Verify that you set the VGRemoteIPHeader parameter to match the header
  that you use, default is X-Forwarded-For

Is the request logged with the correct, rewritten IP ?

**Comment by legecha** [comment]
Hi, thanks for the reply. This is the config I am using:

```
<IfModule mod_vgremoteip.c>
 VGRemoteIPHeader X-Forwarded-For
 VGTrustedProxy 10.190.254.0/23
</IfModule>
```

These are cloud load balancers in the Rackspace London network.

After I added this and restarted Apache the correct IPs are shown in access and error logs.

**Comment by olesku** [comment]
If the correct IP is logged then it's very strange that the deny/allow rule don't act up on it.
Are you sure that you configuration is not overridden somewhere ?

Im not able to reproduce the problem here (Apache/2.2.15).
What Apache version are you running ?

Feel free to contact me on IRC (EFNet / Freenode), nick oles.

**Comment by legecha** [comment]
Yeah - I've just compared the access log for an unrestricted page and the error log when I try load it:

**Access log:**

```
123.45.67.89 - - [23/Jun/2014:23:00:01 +0100] "GET / HTTP/1.1" 200 20577 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36"
123.45.67.89 - - [23/Jun/2014:23:00:14 +0100] "GET /admin HTTP/1.1" 403 289 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36"
```

**Error log:**

```
[Mon Jun 23 23:00:14 2014] [error] [client 123.45.67.89] client denied by server configuration: /home/user/apache/sitename.tld/public/admin
```

```
$httpd -v
Server version: Apache/2.2.15 (Unix)
```

I'll jump on IRC, thanks.

**Comment by legecha** [comment]
Also note that if I use `SetEnvIf X-Forwarded-For "123.45.67.89" ALLOWED_IP` and then `Allow from env=ALLOWED_IP` in the same config directive it works as expected, so I'd guess it's not being overridden elsewhere.

I'm LeonardChallis on IRC - where will I find you?

**Comment by legecha** [comment]
I have tried again with a very similar config to yours: http://pastebin.com/97x9EB30 (I setup an unused domain so that it can be tested easily)

My tests proved unsuccessful though. I am on IRC if you're around at all today.

**Comment by legecha** [comment]
Thanks for sorting this... 3 years ago! 😆
